import { z } from "zod";

export const analyticsEventNameSchema = z.enum([
  "page_view",
  "homepage_view",
  "collection_view",
  "product_view",
  "product_image_interaction",
  "product_video_play",
  "search",
  "search_result_click",
  "zero_search_results",
  "filter_applied",
  "filter_removed",
  "sort_changed",
  "wishlist_added",
  "wishlist_removed",
  "add_to_cart",
  "remove_from_cart",
  "cart_quantity_changed",
  "cart_view",
  "coupon_applied",
  "coupon_failed",
  "begin_checkout",
  "checkout_step_completed",
  "serviceability_checked",
  "address_submitted",
  "payment_initiated",
  "payment_success",
  "payment_failed",
  "payment_cancelled",
  "payment_pending",
  "payment_retry",
  "order_created",
  "purchase",
  "track_order",
  "review_started",
  "review_submitted",
  "whatsapp_clicked",
  "newsletter_subscribed",
  "policy_viewed",
]);
export type AnalyticsEventName = z.infer<typeof analyticsEventNameSchema>;

/** Every field is optional except name/timestamp/session/visitor — events only carry what's relevant. */
export const analyticsEventSchema = z.object({
  name: analyticsEventNameSchema,
  timestamp: z.string().datetime(),
  sessionId: z.string(),
  visitorId: z.string(),
  customerId: z.string().optional(),
  productId: z.string().optional(),
  variantId: z.string().optional(),
  collectionId: z.string().optional(),
  quantity: z.number().int().optional(),
  price: z.number().optional(),
  discount: z.number().optional(),
  cartValue: z.number().optional(),
  orderValue: z.number().optional(),
  currency: z.literal("INR").optional(),
  orderId: z.string().optional(),
  couponCode: z.string().optional(),
  campaignId: z.string().optional(),
  affiliateCode: z.string().optional(),
  utmSource: z.string().optional(),
  utmMedium: z.string().optional(),
  utmCampaign: z.string().optional(),
  utmContent: z.string().optional(),
  utmTerm: z.string().optional(),
  referrer: z.string().optional(),
  pagePath: z.string(),
  deviceCategory: z.enum(["mobile", "tablet", "desktop"]),
  metadata: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])).optional(),
});
export type AnalyticsEvent = z.infer<typeof analyticsEventSchema>;

export const analyticsBatchRequestSchema = z.object({
  events: z.array(analyticsEventSchema).min(1).max(25),
});
export type AnalyticsBatchRequest = z.infer<typeof analyticsBatchRequestSchema>;
